# Generated by Django 5.0.2 on 2024-02-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_organization_alter_user_created_on_alter_user_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='org_id',
            new_name='org',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='org_id',
            new_name='org',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role_id',
            new_name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.SmallIntegerField(default=0),
        ),
    ]
